---
- name: Add public key for {{ user_name }}
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ ssh_public_key  }}"
- name: Add private key for {{ user_name }}
  copy:
    content: "{{ ssh_private_key }}"
    dest: "/home/{{ user_name }}/.ssh/id_rsa"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600
  no_log: true
